name: AIOps Automatic Remediation

on:
  repository_dispatch:
    types:
      - cpu_alert
      - service_alert


jobs:

  remediation:

    runs-on: self-hosted


    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Verify EC2 environment
      run: |
        echo "Running on EC2"
        hostname
        python3 --version
        ansible --version
        aws --version


    - name: CPU Auto Scaling remediation
      if: github.event.action == 'cpu_alert'
      run: |
        echo "CPU overload detected"
        echo "Launching Auto Scaling remediation"
        ansible-playbook playbooks/scale_out.yml


    - name: Service remediation
      if: github.event.action == 'service_alert'
      run: |
        echo "Service failure detected"
        ansible-playbook playbooks/service_fix.yml

